### ISSUE TITLE
Syslog Drain Binder may not exist anymore

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/docs-running-cf#102]
https://github.com/cloudfoundry/docs-running-cf/blob/89744b3f9eb5a24d4028dd46a5edb9f52393ad70/managing-cf/logging-config.html.md.erb#L444-L538

**Comment by ctlong** [comment]
Here it is again
https://github.com/cloudfoundry/docs-running-cf/blob/89744b3f9eb5a24d4028dd46a5edb9f52393ad70/all_metrics.html.md.erb#L35-L38

**Comment by pspinrad** [comment]
Yes, that component isn't there anymore -- discussed [here in CF Slack](https://cloudfoundry.slack.com/archives/CUW93AF3M/p1722429042663059?thread_ts=1722369698.331699&cid=CUW93AF3M) and updated [the page](https://docs.cloudfoundry.org/running/all_metrics.html#syslog) accordingly.
