### ISSUE TITLE
"Audit Events" Documentation references an outdated community plugin

### ISSUE THREAD

**Issue by JenniferStamm** [cloudfoundry/docs-running-cf#125]
Hi cf team, 

the following docs have a note implying that this community plugin would be useful:
https://github.com/cloudfoundry/docs-running-cf/blob/956e8c0c5a160a3c031b478eb7c218d16a731c2f/managing-cf/audit-events.html.md.erb#L102

However, its installation failed for me with 
```
signal: segmentation fault
File is not a valid cf CLI plugin binary.
```

The latest commit on the repository is from 7 years ago, while I'm using the latest cf cli version `8.7.11+b1b4068.2024-07-09` on a Mac with an M chip. I assume the plugin is incompatible either with the cli version or its OSX binary is not compatible with Apple's new chips. 

Would you kindly consider 
- investigating whether my assumptions are correct,
- adding the info to the note if incompatibility confirmed, or
- just removing the note all-together since the plugin seems unmaintained

to avoid that anyone else runs into the same issue?

**Comment by pspinrad** [comment]
Yes, that plugin is obsolete for ARM-based Mac -- discussed [here in CF Slack](https://cloudfoundry.slack.com/archives/C07C04W4Q/p1722397293088599?thread_ts=1722368394.986049&cid=C07C04W4Q) and updated [the page](https://docs.cloudfoundry.org/running/managing-cf/audit-events.html#view-events) accordingly.
