### ISSUE TITLE
Missing description of space quotas

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-running-cf#13]
Space quotas were delivered on Aug 18 2014, but don't yet appear onto https://docs.cloudfoundry.org/running/managing-cf/quota-plans.html into https://github.com/cloudfoundry/docs-running-cf/blob/0b1a0d91574e26f9c9fbc5acb6581a6d65a16c5c/managing-cf/quota-plans.html.md.erb

Details of the epic and completed stories:
https://www.pivotaltracker.com/epic/show/1292082

Output of CLI related support
```
$ cf help
[...]
SPACE ADMIN:
   space-quotas                           List available space resource quotas
   space-quota                            Show space quota info
   create-space-quota                     Define a new space resource quota
   update-space-quota                     update an existing space quota
   delete-space-quota                     Delete a space quota definition and unassign the space quota from all spaces
   set-space-quota                        Assign a space quota definition to a space
   unset-space-quota                      Unassign a quota from a space
```

**Comment by abbyachau** [comment]
Thank you, gberche-orange! We've edited the page to include space quotas.

**Comment by gberche-orange** [comment]
great thanks @abbyachau !
