### ISSUE TITLE
CC API 429 errors missing from list of error codes

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/docs-running-cf#29]
Hi everyone,

We noticed the other day that the 429 errors that Cloud Controller returns when a user has been rate limited are not included in the following list of error codes:
[https://docs.cloudfoundry.org/running/troubleshooting/error-codes.html](
https://docs.cloudfoundry.org/running/troubleshooting/error-codes.html)

It is mentioned on this page, however:
[https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html](https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html)

We just found the list of error codes through a web search so I'm not sure if it's still a maintained list or not, just wanted to let you all know.

Thanks! 👍

**Comment by bentarnoff** [comment]
Hey @tcdowney thanks for bringing this to our attention. It looks like the topic you identified is obsolete, along with a couple of others, so we've removed them. I'm closing this issue but please feel free to get in touch if you have any further feedback.
