### ISSUE TITLE
cc api rate limiting docs incomplete

### ISSUE THREAD

**Issue by MichaelTrestman** [cloudfoundry/docs-running-cf#30]
Hello docs team. These docs around CC API rate-limiting are a little incomplete/misleading: https://docs.cloudfoundry.org/running/rate-limit-cloud-controller-api.html

They say that rate limiting is by IP, but this only true if no user is authenticated. If the CF client has authenticated a UAA user, then rate limiting is per UAA user.
We clarified this with CAPI on slack:
https://cloudfoundry.slack.com/archives/C07C04W4Q/p1490720207020633

**Comment by bentarnoff** [comment]
Thanks, @MichaelTrestman. We updated this topic and the change should be live soon.
