### ISSUE TITLE
StagingStartRequestsReceived Metric incorrect/not emitted

### ISSUE THREAD

**Issue by MirahImage** [cloudfoundry/docs-running-cf#61]
Hi CF docs team, 

We were looking at the [Diego stager metrics](https://docs.cloudfoundry.org/running/all_metrics.html#stager) and noticed that the `StagingStartRequestsReceived` metric is incorrect. We believe the correct metric is `stage.request` or `staging.requested`. 

https://github.com/cloudfoundry/docs-running-cf/blob/master/metrics/_diego.html.md.erb#L216

Best,
Mirah and @gmrodgers

**Comment by selzoc** [comment]
@MirahImage CAPI here, I tracked down the story where this changed: https://www.pivotaltracker.com/n/projects/966314/stories/145950435

So `StagingStartRequestsReceived` was indeed replaced with `staging.requested`.  The story has 4 other replacements that may be worthwhile to double-check.

Thanks,
Chris

**Comment by pspinrad** [comment]
@MirahImage @selzoc finally updated these-- thanks! https://github.com/cloudfoundry/docs-running-cf/commit/aa010f5028e1324b9ad4af62c2dfc842b680f715
