### ISSUE TITLE
CF Logging Document refers to cf-release and metron-agent

### ISSUE THREAD

**Issue by heyjcollins** [cloudfoundry/docs-running-cf#62]
Noticed the docs on [this page](https://docs.cloudfoundry.org/running/managing-cf/logging.html) are outdated and need a refresh.

Probably best to reach out to the Loggregator team to rewrite this page.
CF-Release references should certainly be removed.
Reach out to Release Integration as well if you need anything more/different than the Loggregarians can provide.

So. Yeah.

**Comment by mlimonczenko** [comment]
Hello @heyjcollins,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
