### ISSUE TITLE
cf api - does not list the endpoint

### ISSUE THREAD

**Issue by kiranshashiny** [cloudfoundry/docs-running-cf#87]
$ cf api
No api endpoint set. Use 'cf api' to set an endpoint

==
I am trying to view my end point and I thought that this tells my end point .
What is the exact command to get my end point ?

**Comment by kiranshashiny** [comment]
Any Update on this ?

**Comment by mlimonczenko** [comment]
Hello @kiranshashiny,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
