### ISSUE TITLE
Usage and audit events docs should be updated to describe v3 endpoints instead of v2

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/docs-running-cf#97]
The [usage events](https://github.com/cloudfoundry/docs-running-cf/blob/15b574256f7d1f3be7c0840cadb3b0fbe7acba94/managing-cf/usage-events.html.md.erb#L25-L72) and [audit events](https://github.com/cloudfoundry/docs-running-cf/blob/15b574256f7d1f3be7c0840cadb3b0fbe7acba94/managing-cf/audit-events.html.md.erb#L40-L125) documentation pages both describe how to use v2 endpoints to retrieve events. Per the cloud controller API docs, these endpoints are deprecated (see [here](https://apidocs.cloudfoundry.org/15.3.0/#app-usage-events) and [here](https://apidocs.cloudfoundry.org/15.3.0/#events)) and API clients are encouraged to use the v3 endpoints instead.

We should update these two docs pages to use v3 endpoints instead of v2.

**Comment by mlimonczenko** [comment]
Hello @jenspinney,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
